# Generated by Django 4.0.4 on 2022-05-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='static/profile_image/'),
        ),
    ]
