# Generated by Django 4.0.4 on 2022-05-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_attendee_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='training_img',
        ),
        migrations.AddField(
            model_name='attendee',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='imges/'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='profile_img',
            field=models.ImageField(default='api/static/profile_img/default.png', upload_to='static/profile_img/'),
        ),
    ]
