# Generated by Django 4.0.4 on 2022-05-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_attendee_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='profile_img',
            field=models.ImageField(default='api/static/profile_img/default.png', upload_to='api/static/profile_img/'),
        ),
    ]
