# Generated by Django 4.0.4 on 2022-05-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_attendee_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='image',
            field=models.ImageField(default='imges/default.png', upload_to='imges/'),
        ),
    ]
