# Generated by Django 4.0.4 on 2022-05-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_attendee_email_alter_attendee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
