# Generated by Django 4.0.4 on 2022-05-21 08:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_attendee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='day',
            field=models.IntegerField(default=api.models.AttendanceLog.current_day),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='month',
            field=models.IntegerField(default=api.models.AttendanceLog.current_month),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='year',
            field=models.IntegerField(default=api.models.AttendanceLog.current_year),
        ),
    ]
