# Generated by Django 4.0.4 on 2022-05-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_attendancelog_day_attendancelog_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='address',
            field=models.CharField(blank=True, default='Update address', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='class_sec',
            field=models.CharField(blank=True, default='update', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='pin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
