# Generated by Django 4.0.4 on 2022-05-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_attendee_address_attendee_class_sec_attendee_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
